### ISSUE TITLE
Community Store 2.1.4 & Concrete5 v8.5.0

### ISSUE THREAD

**Issue by justynpride** [JeRoNZ/community_store_order_history#1]
Hi. Does this add on work with the latest version of community store and C5? When i click on the order to view it's details I get an error message of 

Whoops \ Exception \ ErrorException (E_ERROR)
Class 'Concrete\Package\CommunityStore\Src\Attribute\Key\StoreOrderKey' not found

Thought it worth reporting.

**Comment by JeRoNZ** [comment]
I think this package pre dates version 2 of the community store so that probably explains the error. I'll need to recode it quite possibly.

**Comment by justynpride** [comment]
Thanks. I assumed it wasn't down to me, and just a difference between the new versions.
